#!/bin/zsh
for i in $@
{
	control=$((control+1))
	if [[ $i =~ ^[-.*] ]]; then
		if [[ $i =~ [.*!]$ ]]; then
			PARAMETROS_CONF+=("${i//!/}")
			ARGREFUSED+=([$control]="${(P)control}")
		elif [[ $i =~ [.*:]$ ]]; then
			PARAMETROS_ARG+=("${i//:/}")
			ARGREFUSED+=([$control]="${(P)control}")
		else
			if [[ "$PARAMETROS_ARG[@]" =~ "${i}" ]]; then
				ARGUMENTOS+=([${i//-}]="${(P)$((control+1))}")
				ARGREFUSED+=([$control]="${(P)control}")
				ARGREFUSED+=([$((control+1))]="${(P)$((control+1))}")
			elif [[ "$PARAMETROS_CONF[@]" =~ "${i}" ]]; then
				ARGUMENTOS+=([${i//-}]="true")
				ARGREFUSED+=([$control]="${(P)control}")
			fi
		fi
	fi
}

