#!/bin/sh
# if [ $(mp -cmd get.socks |wc -l) -ne 0 ]; then
# 	for x in $(mp -cmd get.socks) 
# 	{
# 		sock=$x
# 		if mp -cmd "sock.ativo"; then
# 			if [ $(mp -cmd playlist |sed 's/,/\n/g'|grep '"playing":true') ]; then
# 				if [ $(echo '{ "command": ["get_property", "pause"] }' |socat - $sock |grep 'true') ];then
# 					trck=$(mp -cmd trackget)
# 					printf '%-20s %10s' "  $(mp -cmd title|tail -c 12)" "| %{F$mprefixcolor}%{F-} $trck |  "
# 				else
# 					trck=$(mp -cmd trackget)
# 					printf '%-20s %10s' "  $(mp -cmd title|tail -c 12)" "| %{F$mprefixcolor}%{F-} $trck |  "					
# 				fi
# 			else
# 				printf '%-20s %10s' " ... " "|  |  "
# 				continue
# 			fi
# 		fi 
# 	}
# else
# 	printf '%-10s %10s' " ... " "|  |  "
# fi
# cat /tmp/mpinfo

if mp -cmd "sock.ativo"; then
	if [ $(mp -cmd playlist |sed 's/,/\n/g'|grep '"playing":true') ]; then
		if [ $(echo '{ "command": ["get_property", "pause"] }' |socat - /tmp/mpvsocketDefault |grep 'true') ];then
			trck=$(mp -cmd trackget)
			printf '%-20s %10s' "  $(mp -cmd title|tail -c 12)" "| %{F$mprefixcolor}%{F-} $trck |  "
		else
			trck=$(mp -cmd trackget)
			printf '%-20s %10s' "  $(mp -cmd title|tail -c 12)" "| %{F$mprefixcolor}%{F-} $trck |  "					
		fi
	else
		printf '%-20s %10s' " ... " "|  |  "
		continue
	fi
fi 
